const RULES={decks:6,dealerHitsSoft17:false,blackjackPayout:1.5,insurancePayout:2,startingBalance:1000,minBet:5,maxBet:500};
const suits=[['♠','black'],['♥','red'],['♦','red'],['♣','black']], ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const $=s=>document.querySelector(s); let shoe=[],balance=RULES.startingBalance,bet=0,betChips=[],roundChips=[],hands=[],dealer=[],active=0,state='betting',insurance=0,soundOn=true,wagerCleared=false;
const el={balance:$('#balance'),bet:$('#current-bet'),tableBet:$('#table-bet'),wagerDisplay:$('#wager-display'),wagerStacks:$('#wager-stacks'),outcomeFx:$('#outcome-fx'),dealer:$('#dealer-cards'),dealerScore:$('#dealer-score'),hands:$('#hands'),message:$('#message'),betPanel:$('#betting-panel'),actions:$('#play-actions'),newRound:$('#new-round')};
const crowdWin=new Audio('assets/audio/crowd-win.ogg'),crowdLossVoices=Array.from({length:4},()=>new Audio('assets/audio/crowd-loss.ogg'));

function money(n){return `₪${Number(n).toLocaleString('he-IL',{maximumFractionDigits:2})}`}
function createShoe(){shoe=[];for(let d=0;d<RULES.decks;d++)for(const [suit,color] of suits)for(const rank of ranks)shoe.push({suit,color,rank});for(let i=shoe.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shoe[i],shoe[j]]=[shoe[j],shoe[i]]}}
function draw(){if(shoe.length<78)createShoe();return shoe.pop()}
function value(cards){let total=0,aces=0;cards.forEach(c=>{if(c.rank==='A'){aces++;total+=11}else total+=['J','Q','K'].includes(c.rank)?10:+c.rank});while(total>21&&aces){total-=10;aces--}return{total,soft:aces>0}}
function isBlackjack(hand){return hand.cards.length===2&&value(hand.cards).total===21&&!hand.split}
function beep(freq=420,duration=.06){if(!soundOn)return;const C=window.AudioContext||window.webkitAudioContext,ctx=beep.ctx||(beep.ctx=new C),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}
function primeCrowdAudio(){[crowdWin,...crowdLossVoices].forEach(audio=>{audio.muted=true;audio.play().then(()=>{audio.pause();audio.currentTime=0;audio.muted=false}).catch(()=>{audio.muted=false})})}
function applause(){if(!soundOn)return;crowdWin.pause();crowdWin.currentTime=0;crowdWin.volume=.72;crowdWin.play().catch(()=>{});setTimeout(()=>{crowdWin.pause();crowdWin.currentTime=0},4200)}
function disappointment(){if(!soundOn)return;crowdLossVoices.forEach((audio,index)=>{audio.pause();audio.currentTime=0;audio.volume=.3;audio.playbackRate=.88+index*.08;setTimeout(()=>audio.play().catch(()=>{}),index*65)})}
function cardHTML(c,hidden=false){const delay=c.dealDelay||'0ms';if(hidden)return`<div class="card card-hidden" style="--deal-delay:${delay}" aria-label="קלף מוסתר"><div class="card-inner"><span class="card-face card-back"></span></div></div>`;const fresh=!c.revealed;c.revealed=true;return`<div class="card ${fresh?'deal-flip':''}" style="--deal-delay:${delay}" aria-label="${c.rank} ${c.suit}"><div class="card-inner"><span class="card-face card-back"></span><span class="card-face card-front ${c.color}"><span class="corner">${c.rank}<small>${c.suit}</small></span><span class="suit-center">${c.suit}</span></span></div></div>`}
function wagerTotal(){return hands.length?hands.reduce((sum,hand)=>sum+hand.bet,0):bet}
function chipsForAmount(amount){const result=[];for(const value of [100,50,25,5])while(amount>=value){result.push(value);amount-=value}return result}
function renderWager(){const cleared=state==='settled'&&wagerCleared,chips=cleared?[]:(state==='betting'?betChips:roundChips),total=cleared?0:wagerTotal();el.bet.textContent=money(total);el.tableBet.textContent=money(total);el.wagerDisplay.classList.toggle('empty',total===0);const groups=[5,25,50,100].map(value=>({value,count:chips.filter(chip=>chip===value).length})).filter(group=>group.count);el.wagerStacks.innerHTML=groups.map(group=>`<button class="wager-stack chip-${group.value}" data-value="${group.value}" ${state!=='betting'?'disabled':''} aria-label="${state==='betting'?'הסר':'ערמת'} ז׳יטון ${group.value}"><span class="stacked-chips" aria-hidden="true">${Array.from({length:Math.min(group.count,6)},(_,index)=>`<i style="--stack-index:${index}"></i>`).join('')}</span><b>${group.value}</b><em>×${group.count}</em></button>`).join('');$('#undo-chip').disabled=state!=='betting'||!betChips.length}
function render(reveal=false){el.balance.textContent=money(balance);renderWager();const concealing=state==='playing'||state==='dealing';el.dealer.innerHTML=dealer.map((c,i)=>cardHTML(c,!reveal&&concealing&&i===1)).join('');const shown=concealing&&!reveal?[dealer[0]]:dealer;el.dealerScore.textContent=shown.length?value(shown).total:'';el.hands.innerHTML=hands.map((h,i)=>`<div class="hand ${i===active&&state==='playing'?'active':''}"><div class="hand-title"><span>${hands.length>1?'יד '+(i+1):'השחקן'}</span><output class="score">${value(h.cards).total}</output></div><div class="cards">${h.cards.map(c=>cardHTML(c)).join('')}</div><div class="hand-result">${h.result||''}</div></div>`).join('');updateActions()}
function setMessage(text,result=false){el.message.textContent=text;el.message.classList.toggle('result',result)}
function updateActions(){if(state!=='playing'||!hands[active])return;const h=hands[active],two=h.cards.length===2;$('#double').disabled=!(two&&balance>=h.bet);$('#split').disabled=!(two&&hands.length===1&&h.cards[0].rank===h.cards[1].rank&&balance>=h.bet)}
function setView(mode){el.betPanel.classList.toggle('hidden',mode!=='betting');el.actions.classList.toggle('hidden',mode!=='playing');el.newRound.classList.toggle('hidden',mode!=='settled')}
function addBet(amount){if(state!=='betting')return;if(bet+amount>Math.min(balance,RULES.maxBet)){setMessage('לא ניתן להגדיל את ההימור');return}bet+=amount;betChips.push(amount);beep(260);render()}
document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>addBet(+c.dataset.value));
function removeChip(value){if(state!=='betting')return;const index=value===undefined?betChips.length-1:betChips.lastIndexOf(value);if(index<0)return;bet-=betChips[index];betChips.splice(index,1);beep(190);render();setMessage(bet?'ההימור עודכן':"בחרו ז'יטונים והניחו הימור")}
el.wagerStacks.onclick=event=>{const stack=event.target.closest('.wager-stack');if(stack)removeChip(+stack.dataset.value)};
$('#undo-chip').onclick=()=>removeChip();
$('#clear-bet').onclick=()=>{bet=0;betChips=[];render();setMessage("בחרו ז'יטונים והניחו הימור")};
$('#deal').onclick=deal;
function deal(){if(bet<RULES.minBet){setMessage(`הימור מינימלי: ${money(RULES.minBet)}`);return}wagerCleared=false;el.outcomeFx.innerHTML='';balance-=bet;roundChips=[...betChips];const playerFirst=draw(),dealerFirst=draw(),playerSecond=draw(),dealerSecond=draw();playerFirst.dealDelay='80ms';dealerFirst.dealDelay='390ms';playerSecond.dealDelay='700ms';dealerSecond.dealDelay='1010ms';hands=[{cards:[playerFirst,playerSecond],bet,result:'',split:false}];dealer=[dealerFirst,dealerSecond];active=0;state='dealing';setView(state);setMessage('הדילר מחלק את הקלפים');beep(520);render();setTimeout(()=>{state='playing';setView(state);setMessage('היד שלכם');render();if(dealer[0].rank==='A')openInsurance();else checkNaturals()},1650)}
function openInsurance(){const dlg=$('#insurance-dialog');$('#take-insurance').disabled=balance<hands[0].bet/2;dlg.showModal()}
$('#take-insurance').onclick=()=>{insurance=hands[0].bet/2;balance-=insurance;$('#insurance-dialog').close();checkNaturals()};
$('#decline-insurance').onclick=()=>{$('#insurance-dialog').close();checkNaturals()};
function checkNaturals(){const dbj=isBlackjack({cards:dealer,split:false}),pbj=isBlackjack(hands[0]);if(dbj||pbj){if(dbj&&insurance){balance+=insurance*(RULES.insurancePayout+1)}if(dbj&&pbj){balance+=hands[0].bet;hands[0].result='תיקו'}else if(pbj){balance+=hands[0].bet*(RULES.blackjackPayout+1);hands[0].result='BLACKJACK!'}else hands[0].result='הדילר ניצח';settle('הסיבוב הסתיים')}else{if(insurance)setMessage('אין לדילר Blackjack — הביטוח הפסיד');render()}}
$('#hit').onclick=()=>{const h=hands[active];h.cards.push(draw());beep(500);render();const v=value(h.cards).total;if(v>=21){if(v>21)h.result='נשרפת';advanceHand()}else setMessage('קלף נוסף או עצירה?')};
$('#stand').onclick=()=>advanceHand();
$('#double').onclick=()=>{const h=hands[active],added=h.bet;balance-=added;roundChips.push(...chipsForAmount(added));h.bet*=2;h.cards.push(draw());beep(390);render();if(value(h.cards).total>21)h.result='נשרפת';advanceHand()};
$('#split').onclick=()=>{const h=hands[0],stake=h.bet;balance-=stake;roundChips.push(...chipsForAmount(stake));const second=h.cards.pop();h.split=true;hands.push({cards:[second],bet:stake,result:'',split:true});h.cards.push(draw());hands[1].cards.push(draw());beep(620);render();if(h.cards[0].rank==='A'){hands.forEach(x=>x.result=value(x.cards).total===21?'21':'');dealerTurn()}else setMessage('משחקים כעת את היד הראשונה')};
function advanceHand(){if(active<hands.length-1){active++;setMessage(`משחקים כעת את יד ${active+1}`);render()}else dealerTurn()}
function dealerTurn(){state='dealer';setView('dealer');render(true);const live=hands.some(h=>value(h.cards).total<=21);if(live){const timer=setInterval(()=>{const v=value(dealer);if(v.total<17||(v.total===17&&v.soft&&RULES.dealerHitsSoft17)){dealer.push(draw());beep(440);render(true)}else{clearInterval(timer);resolveHands()}},520)}else resolveHands()}
function resolveHands(){const dv=value(dealer).total;hands.forEach(h=>{const pv=value(h.cards).total;if(pv>21)h.result='נשרפת';else if(dv>21||pv>dv){balance+=h.bet*2;h.result=dv>21?'הדילר נשרף — זכית':'זכית'}else if(pv===dv){balance+=h.bet;h.result='תיקו'}else h.result='הדילר ניצח'});settle(hands.some(h=>h.result.includes('זכית'))?'זכייה!':'הסיבוב הסתיים')}
function runOutcomeAnimation(outcome){el.outcomeFx.innerHTML='';if(outcome==='win'){el.outcomeFx.className='outcome-fx win-fx';el.outcomeFx.innerHTML='<img class="dealer-hand-img" src="assets/dealer-hand.png" alt="">'+Array.from({length:18},(_,index)=>`<i class="payout-chip chip-${[5,25,50,100][index%4]}" style="--chip-x:${(index%7-3)*24}px;--chip-delay:${(index%6)*.055}s"></i>`).join('');applause()}else if(outcome==='loss'){el.outcomeFx.className='outcome-fx loss-fx';el.outcomeFx.innerHTML='<img class="dealer-hand-img" src="assets/dealer-hand.png" alt=""><div class="swept-chips"></div>';disappointment()}setTimeout(()=>{wagerCleared=true;bet=0;betChips=[];roundChips=[];renderWager()},1200);setTimeout(()=>{el.outcomeFx.className='outcome-fx';el.outcomeFx.innerHTML=''},2300)}
function settle(msg){state='settled';insurance=0;setView(state);setMessage(msg,true);render(true);const won=hands.some(h=>h.result.includes('זכית')||h.result.includes('BLACKJACK')),push=hands.every(h=>h.result==='תיקו');runOutcomeAnimation(won?'win':push?'push':'loss')}
$('#new-round').onclick=()=>{bet=0;betChips=[];roundChips=[];wagerCleared=false;hands=[];dealer=[];state='betting';setView(state);setMessage("בחרו ז'יטונים והניחו הימור");if(balance<RULES.minBet)balance=RULES.startingBalance;render()};
$('#sound-toggle').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'♪':'×';e.currentTarget.setAttribute('aria-label',soundOn?'כיבוי צלילים':'הפעלת צלילים')};
$('#help-toggle').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();
$('#enter-game').onclick=()=>{$('#welcome-dialog').close();primeCrowdAudio();beep(620,.1)};
createShoe();setView('betting');render();if(!new URLSearchParams(location.search).has('skipWelcome'))$('#welcome-dialog').showModal();
